// import "./globals.css";
import { Providers } from "@/redux/provider";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const defaultTheme = createTheme();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ThemeProvider theme={defaultTheme}> */}
          <Navbar />
          <Providers>
            {children}     
          </Providers>
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
  );
}
