import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from "@/redux/provider";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body>
=======
      <body className={inter.className}>
>>>>>>> main
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
